font_family				Terminal
font_size				10
bold_font				auto
italic_font				auto
bold_italic_font		auto
remember_window_size	no
initial_window_width	800
initial_window_height	600
window_padding_width	5
background				#009D71
background_opacity		0.30
foreground				#FDFBD4
map						ctrl+c copy_to_clipboard
map						ctrl+v paste_from_clipboard