alang=jpn,spa,eng
slang=spa,eng
save-position-on-quit=yes
write-filename-in-watch-later-config=yes
keep-open=no
idle=once
volume=100
volume-max=130
cursor-autohide=200
osd-font='sans'
osd-font-size=20
screenshot-directory="~/Imágenes/Capturas de pantalla/"