#!/usr/bin/env bash

export XDG_SESSION_TYPE=x11
export TERMINAL=kitty
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export SDL_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export GLFW_IM_MODULE=ibus

fcitx5 -r -d &
copyq &

export ENTORNO=${1:-'qtile-dev'}

case "$ENTORNO" in
	'qtile'|'qtile-dev')
		xrdb -merge ~/.Xresources
		dato=$(xrdb -query | grep Xft.dpi | tr ' \t' ' ')
		export QT_FONT_DPI=$(echo "$dato" | cut -d ' ' -f2)
		export QT_SCALE_FACTOR=$(echo "$dato" | cut -d ' ' -f4)
		export GTK_THEME=Nordic
		export GTK_ICON_THEME=Papirus

		picom &
		dunst &
		gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &
		blueman-applet &
		qtile start
		;;
	*)
		echo "Entorno de escritorio desconocido: $ENTORNO"
		exit 1
		;;
esac