Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
        Option "TappingButtomMap" "lrm"
        Option "NaturalScrolling" "true"
        Option "ClickMethod" "buttonareas"
        Option "ClickMethod" "clickfinger"
EndSection